# Generated by Django 2.2.4 on 2019-08-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='username',
        ),
    ]
