# Generated by Django 2.2.4 on 2019-08-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_study', '0002_auto_20190826_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='username',
            new_name='name',
        ),
    ]
